/// Flutter icons Emotion
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Emotion
///      fonts:
///       - asset: fonts/Emotion.ttf
///
/// 
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
///
import 'package:flutter/widgets.dart';

class Emotion {
  Emotion._();

  static const _kFontFam = 'Emotion';

  static const IconData emo_happy = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData emo_wink = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData emo_unhappy = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData emo_sleep = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData emo_thumbsup = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData emo_devil = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData emo_surprised = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData emo_tongue = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData emo_coffee = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData emo_sunglasses = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData emo_displeased = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData emo_beer = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData emo_grin = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData emo_angry = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData emo_saint = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData emo_cry = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData emo_shoot = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData emo_squint = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData emo_laugh = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData emo_wink2 = IconData(0xe813, fontFamily: _kFontFam);
}
